#!/bin/bash
# AI Menu Extraction Environment Setup Script

echo "🤖 Setting up AI Menu Extraction System Environment Variables"
echo "=========================================================="

# Check if .env file exists
if [ -f ".env" ]; then
    echo "✅ .env file already exists"
else
    echo "⚠️  .env file not found. Please create one with your API keys."
fi

echo ""
echo "📝 REQUIRED ENVIRONMENT VARIABLES:"
echo ""
echo "1. For OpenAI Vision API (RECOMMENDED - Best Results):"
echo "   export OPENAI_API_KEY='your_openai_api_key_here'"
echo ""
echo "2. For Google Vision API (FALLBACK - Free Alternative):"
echo "   export GOOGLE_APPLICATION_CREDENTIALS='path/to/your/service-account.json'"
echo ""
echo "📋 SETUP INSTRUCTIONS:"
echo ""
echo "Option 1 - Temporary (for current session):"
echo "   export OPENAI_API_KEY='your_actual_openai_key'"
echo ""
echo "Option 2 - Permanent (add to ~/.zshrc or ~/.bashrc):"
echo "   echo 'export OPENAI_API_KEY=\"your_actual_openai_key\"' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "Option 3 - Create .env file:"
echo "   echo 'OPENAI_API_KEY=your_actual_openai_key' > .env"
echo ""
echo "🔧 HOW TO GET API KEYS:"
echo ""
echo "OpenAI API Key:"
echo "   1. Go to https://platform.openai.com/api-keys"
echo "   2. Click 'Create new secret key'"
echo "   3. Copy the key and replace 'your_actual_openai_key'"
echo ""
echo "Google Vision API:"
echo "   1. Go to Google Cloud Console"
echo "   2. Create or select a project"
echo "   3. Enable Vision API"
echo "   4. Create a Service Account"
echo "   5. Download JSON key file"
echo ""
echo "✅ TESTING THE SETUP:"
echo ""
echo "After setting up the variables, test with:"
echo "   curl -s http://localhost:5000/health | head -10"
echo ""
echo "🎯 SYSTEM STATUS:"
echo "   - Without API keys: System will use basic text parsing"
echo "   - With OpenAI: Best extraction accuracy (recommended)"
echo "   - With Google Vision: Good fallback option (free)"
